name       : haskell-free
version    : 5.0.2
release    : 3
source     :
    - http://hackage.haskell.org/package/free-5.0.2/free-5.0.2.tar.gz : ef05eb1c8e69742a4f962c573ef362e44ad48772940f1ef69fe39f0f77b2a396
license    : BSD-3-Clause
component  : programming.haskell
summary    : Free monads are useful for many tree-like structures and domain specific
    languages.
description: |
    Free monads are useful for many tree-like structures and domain specific languages.
builddeps  :
    - haskell-cabal-install
    - haskell-exceptions
    - haskell-prelude-extras
    - haskell-profunctors
    - haskell-transformers-base
    - haskell-semigroupoids
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
