name       : haskell-free
version    : 5.1.3
release    : 4
source     :
    - https://hackage.haskell.org/package/free-5.1.3/free-5.1.3.tar.gz : 2c70d66e3a1ad52ce4b22d5510ffc6d7b3db950bd7f43bc61801cfe7b24c2e2d
license    : BSD-3-Clause
component  : programming.haskell
summary    : Free monads are useful for many tree-like structures and domain specific languages.
description: |
    Free monads are useful for many tree-like structures and domain specific languages.
builddeps  :
    - haskell-cabal-install
    - haskell-exceptions-devel
    - haskell-profunctors-devel
    - haskell-semigroupoids-devel
    - haskell-transformers-base-devel
rundeps    :
    - devel:
        - haskell-exceptions-devel
        - haskell-profunctors-devel
        - haskell-semigroupoids-devel
        - haskell-transformers-base-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
