name       : haskell-free
version    : 4.12.4
release    : 1
source     :
    - http://hackage.haskell.org/package/free-4.12.4/free-4.12.4.tar.gz : c9fe45aae387855626ecb5a0fea6afdb207143cb00af3b1f715d1032d2d08784
license    : BSD-3-Clause
component  : programming.haskell
summary    : Free monads are useful for many tree-like structures and domain specific languages.
description: |
    Free monads are useful for many tree-like structures and domain specific languages.
builddeps  :
    - haskell-cabal-install
    - haskell-exceptions
    - haskell-prelude-extras
    - haskell-profunctors
    - haskell-semigroupoids
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
